### PR TITLE
Move to static maturity badges

### PR DESCRIPTION
**Pull request by evan2645**
This commit moves us to static maturity badges rather than ones
generated on the fly. Doing so reduces the copy/paste overhead to add or
change badges, and also guards against errors related to the generation
of the badge at load time (which I occasionally observe).

Signed-off-by: Evan Gilman <egilman@vmware.com>

### CODE REVIEW

**Comment by azdagron** [comment]
Oh this is really nice :) Grabbing just the right bits when pasting the glob was a little tedius.

**Comment by evan2645** [comment]
Thanks @amoore877! I received an email notification that you approved this, but it is not showing in the UI .. maybe because of the GH outage today

**Review by amoore877 — APPROVED** [review]
Let's try this github usage again :)

**Comment by evan2645** [comment]
woot!

**Pull request merged**
